### PR TITLE
Added help argument. Partial fix for issue #528

### PR DESCRIPTION
**Pull request by KaKnife**
**Problem**:
Partially resolved issue #528 
No random builtin
**Solution**: 
Implemented Help Flag
Implemented random builtin
**Changes introduced by this pull request**:
- Added Help Flag
- Added random Builtin
**Drawbacks**: 
Does not fully describe each argument
cannot seed random generator

### CODE REVIEW

**Comment by mmstick** [comment]
Thanks!

The random builtin should be modeled after Fish's random builtin[1].

[1] https://fishshell.com/docs/current/commands.html#random

**Comment by KaKnife** [comment]
Thanks for the guidance. Ill add the arguments

**Comment by mmstick** [comment]
Can you run `rustfmt-nightly` on this?

**Comment by mmstick** [comment]
Thanks! Am about to merge this. In the process of squashing.

**Pull request closed without merging**
