### PR TITLE
Call execve from fork_and_exec in sys/redox.rs so they can share code

### PR DESCRIPTION
**Pull request by blackle**
**Problem**: execve and fork_and_exec share a large chunk of code

**Solution**: Remove the argument building and path resolution in fork_and_exec and call execve instead

**Changes introduced by this pull request**:

- There is no more repeated code between fork_and_exec and execve

**Drawbacks**: Ion forks even if the file doesn't exist, whereas before it wouldn't.

**State**: Ready

### CODE REVIEW

**Comment by jackpot51** [comment]
This looks good to me, and it is what the standard library does: https://github.com/redox-os/rust/blob/master/src/libstd/sys/redox/process.rs

**Comment by mmstick** [comment]
The separation was done to ensure that the child of the fork that calls **execve** will not allocate any memory, and the issue being that the pre-existing `execve()` function does precisely that when it constructs its arguments. The allocations to construct the arguments need to be done before the fork is called.

**Comment by jackpot51** [comment]
If the allocations are done before, then both the fork and parent will have copies of the allocated memory. Is there a reason it should not be done after?

**Comment by mmstick** [comment]
@jackpot51 I've noticed that the fish shell goes to great lengths to ensure that no allocations occur within the child of a fork. Their rationale being that `malloc` internally uses a mutex when allocating memory for thread safety, yet that mutex can cause issues when you are mixing threads with forks (which Ion is currently doing).

**Comment by mmstick** [comment]
On another note though, I have been thinking about doing away with Ion's usage of threads, so that it doesn't mix threads with forks at all.

**Comment by jackpot51** [comment]
Ok, feel free to revert this if it is not yet a good idea

**Comment by mmstick** [comment]
I'll keep it, but I'll probably separate the argument-generation logic from the argument-execution logic.

**Pull request merged**
