### PR TITLE
Add semantics for indexing into arrays with negative indices 

### LINKED ISSUE #263: Improve Range Syntax With Negative Values for Taking From the End
To further improve the capabilities of the range syntax, we can expand on that to support the following syntax, where a negative value indicates to count and take values from the end of an array, versus from the beginning

```ion
# Syntax for getting the last value?
echo @array[-1]   # Take the next to last value
echo @array[..-1] # Take all but the last value
echo @array[-5..] # Take the last five values
echo @array[-5..-2]
```

### PR DESCRIPTION
**Pull request by huntergoldstein**
**Problem**: There is no way to refer to, for example, the second to last element of an array aside from `@array[len(array) - 2]` where `len` gets the number of elements in an array.

**Solution**: Extend Ion's syntax to allow for this through negative indices, such as in Python:
```
$ let array = [ 1 2 3 4 5 6 ]
$ echo @array[-1]
6
$ echo @array[1..-2]
2 3 4
```

**Changes introduced by this pull request**:
- Introduce new data structures that represent indexing from the end of an array
- Update parsing of array ranges and indices to use these new structures

**Drawbacks**:
- `parser::shell_expand::words` has become a bit of a mess with a bunch of `Index` named classes everywhere. As discussed in #263 it would be useful to refactor this and move some of the logic repeated at call-sites, but that's a little too broad for a single PR.

**TODOs**: 
- [x] Outstanding bug where `@array[2...-2]` results in an empty output for arrays where it is well defined.
- [x] Add in more regression / unit tests, including failure-like cases

**State**: WIP

**Blocking/related**: Closes #263

### CODE REVIEW

**Comment by huntergoldstein** [comment]
This is ready for review; There is some cleanup to be done but I'm not sure how I feel about saying "It will come with refactoring the `Index` stuff."

**Comment by mmstick** [comment]
It looks good to me. If you want it merged now, I can do that.

**Comment by huntergoldstein** [comment]
Merge away

**Comment by mmstick** [comment]
Thanks! I'm sure it was a lot of work getting adjusted to the codebase.

**Pull request merged**
