### PR TITLE
Migrate to xdg

### LINKED ISSUE #621: Replace app_dirs crate with xdg crate
May be a better choice in the long term.

### PR DESCRIPTION
**Pull request by jD91mZM2**
Fixes #621

### CODE REVIEW

**Comment by jD91mZM2** [comment]
Sorry about the CI fail. When cross-compiling to redox you get  
```Rust
error[E0432]: unresolved import `xdg::BaseDirectories`
 --> src/shell/plugins/mod.rs:9:5
  |
9 | use xdg::BaseDirectories;
  |     ^^^^^^^^^^^^^^^^^^^^ no `BaseDirectories` in the root

error[E0432]: unresolved import `xdg::BaseDirectories`
 --> src/shell/variables/mod.rs:5:5
  |
5 | use xdg::BaseDirectories;
  |     ^^^^^^^^^^^^^^^^^^^^ no `BaseDirectories` in the root

error[E0432]: unresolved import `xdg::BaseDirectories`
  --> src/shell/mod.rs:33:5
   |
33 | use xdg::BaseDirectories;
   |     ^^^^^^^^^^^^^^^^^^^^ no `BaseDirectories` in the root

```

apparently.  
The `xdg` crate doesn't seem to be doing any weird conditional compiling, and the crate works when compiling to x86_64 linux. That's weird.

**Comment by mmstick** [comment]
I think I know what it is. The very first line of code in their `lib.rs` file is this:

```rust
#![cfg(unix)]
```

Which may be preventing this from compiling on Redox?

**Comment by jD91mZM2** [comment]
Ohh, didn't see that! Redox isn't unix?

**Comment by mmstick** [comment]
Maybe you could try forking the project, updating the Cargo.toml here to point to your fork of the project, and change that line to `#[cfg(any(unix, redox))]` to see if that fixes the problem?

**Comment by jD91mZM2** [comment]
But the optimal solution would be for Rust to accept redox as unix, don't you think?

**Comment by jD91mZM2** [comment]
Probably because I updated the whole Cargo.lock. Let's most of revert that.

**Comment by mmstick** [comment]
Thanks! May want to submit a PR to the rust-xdg repository with your changes, too, so that we can get a new release of Ion out soon.

**Comment by jD91mZM2** [comment]
I thought it was too ugly for that, but sure! Thanks for all your help!

**Pull request merged**
