### PR TITLE
Fix typo in --help output

### PR DESCRIPTION
**Pull request by BafDyce**

### CODE REVIEW

**Comment by mmstick** [comment]
You may need to re-submit this PR.

**Comment by BafDyce** [comment]
I just used the 'Update branch' feature on GitHub. Is this enough for you to squash and merge this PR or should I open a completely new PR?

**Comment by mmstick** [comment]
@BafDyce Keep forgetting to merge this. I can merge once CI checks out.

**Comment by BafDyce** [comment]
Updated the branch once again. Don't know why CI never passes..

**Pull request closed without merging**
