### PR TITLE
Clean up and test summary

### PR DESCRIPTION
**Pull request by dcampbell24**
**Problem**:
- Ion does not load a history file
- Default values are being set in an ad-hoc manner rather than implementing the Default trait.
- Some of the documentation wording is awkward.
- Some functions are imported without keeping their module name.
- Ion does not track the execution time of the commands it runs.

I can add more to this. I just want to get it out since I wrote it a while ago now.

### CODE REVIEW

**Comment by dcampbell24** [comment]
```fish
➤ rustup show
Default host: x86_64-unknown-linux-gnu

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
nightly-x86_64-unknown-linux-gnu

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (directory override for '/home/david/code/ion')
rustc 1.13.0-nightly (d4037fc47 2016-09-16)

david@X51:~/c/ion|clean-up-and-test-summary✓                                                                                                            
➤ bash examples/run_examples.sh
Test /home/david/code/ion/examples/advanced_conditions.ion [PASS]
Test /home/david/code/ion/examples/basic_condition.ion [PASS]
Test /home/david/code/ion/examples/comments.ion [PASS]
Test /home/david/code/ion/examples/fail.ion [PASS]
Test /home/david/code/ion/examples/fn.ion [PASS]
Test /home/david/code/ion/examples/for.ion [PASS]
```

**Comment by dcampbell24** [comment]
In order to set the variables HISTORY_FILE_ENABLED or RECORD_SUMMARY add them to your .ionrc file:
```fish
➤ cat ~/.ionrc
let HISTORY_FILE_ENABLED=1
let RECORD_SUMMARY=1
david@X51:~/c/ion|clean-up-and-test-summary✓                                                                                                            
➤ bash examples/run_examples.sh
Test /home/david/code/ion/examples/advanced_conditions.ion [FAIL]
Test /home/david/code/ion/examples/basic_condition.ion [PASS]
Test /home/david/code/ion/examples/comments.ion [PASS]
Test /home/david/code/ion/examples/fail.ion [PASS]
Test /home/david/code/ion/examples/fn.ion [PASS]
Test /home/david/code/ion/examples/for.ion [PASS]
➤ cat ~/.ion_history 
if a == a
echo true a == a
if b != b
echo true b != b
else
echo false b != b
if 3 > 2
echo "true 3 > 2"
else
echo "false 3 > 2"
end
end
#summary# elapsed real time: 0.000813847 seconds
#summary# elapsed real time: 0.000837489 seconds
#summary# elapsed real time: 0.000793361 seconds
else
echo false a == a
end
if 3 == 2
echo fail
else
echo pass
end
#summary# elapsed real time: 0.000859404 seconds
echo Hello world  # End of line comments are ignored
#summary# elapsed real time: 0.000907052 seconds
#echo Goodbye world
if 3 == 2
echo pass
else
echo fail
end
#summary# elapsed real time: 0.000819576 seconds
fn test a b c
echo $a
echo $b
echo $c
end
test hello world goodbye
#summary# elapsed real time: 0.000723706 seconds
#summary# elapsed real time: 0.000736104 seconds
#summary# elapsed real time: 0.000710804 seconds
#summary# elapsed real time: 0.002931649 seconds
for i in 1 2 3 4 5
echo $i
end
#summary# elapsed real time: 0.000808691 seconds
#summary# elapsed real time: 0.000867134 seconds
#summary# elapsed real time: 0.000695805 seconds
#summary# elapsed real time: 0.000801387 seconds
#summary# elapsed real time: 0.000742227 seconds

```

And now I realize I probably need to add tests for the different config file states.

**Comment by jackpot51** [comment]
@dcampbell24 Is this ready for merge?

**Comment by dcampbell24** [comment]
Yea, thanks!

**Pull request merged**
