### PR TITLE
funky grammar proposal

### PR DESCRIPTION
**Pull request by Ticki**

### CODE REVIEW

**Comment by polymetric1** [comment]
Why is there a semicolon after the `let` statement? It makes sense but unnecessary.

**Comment by Ticki** [comment]
If we want to avoid complications with the parser semicolons are a good idea.

**Comment by polymetric1** [comment]
Will the parser execute input line by line?

**Comment by Ticki** [comment]
> Will the parser execute input line by line?

No, that's not what a parser does. It parses it, execution is a whole other process.

**Comment by polymetric1** [comment]
Alright I'm stupid. I have no experience with shell parsers so I should read up on it first

**Comment by Ticki** [comment]
No problem. The process is something like this:

`Program -- Lexer (tokenizer) --> Token list -- Parser --> AST (abstract syntax tree) -- Preprocessor -- Executor --> Output`

**Pull request merged**
