### PR TITLE
WIP: Tab completions

### PR DESCRIPTION
**Pull request by BafDyce**
**IMPORTANT**
This is sorta, kinda WIP and NOT intended to be merged as it is!
The code still needs a few tweaks, and the commits are not meaningful on their own (I just committed all wip-stuff at once when I made breaks). This is more like a proposal and a basis for discussion.

**Problem**:
This PR adds support for tab completions. See  #397

**Solution**:
The general idea: For each application, there is a user-friendly config file (TOML-format) which defines different types of command line parameters, etc. Currently supported features:
- boolean flags (e.g. `--version`)
- paths
- files with specific file extensions
- numbers
- key=value
- string (aka "everything else that takes custom values") with support for options (predefined list of possible values)

If an application has no completion-config, the default file file completer is used.

**Changes introduced by this pull request**:

- New dependencies: toml, serde
- On startup (in `execute_interactive`), available completion-configs are parsed and saved. **For now, this is hardcoded**, as I'm unsure where we should save such files.
- A new completer (`IonCmdCompleter`) was created, similar to the existing `IonFileCompleter`
- When the user hits tab twice and the application (first word on the command line) has a completion defined, it is examined for possible matches.
- I've added a base ("empty") config file as well as two (unfinished) configs for `cargo` and `git`.

**Drawbacks**:
- I don't know if my code structure/architecture is fine, as I figured out how liner works as I worked on this, so the code may be restructured more cleanly?
- Also, I had to add an unsafe (https://github.com/BafDyce/ion/blob/adb13743757078f021614e89a8820958ea15203e/src/lib/shell/completer.rs#L71) to satisfy the borrow checker. Don't know if this can be avoided by restructuring.
- Aliases (different names for the same application) are not handled/implemented yet.

**TODOs**:
- Discuss whether such a config-file based solution is wanted
- Add support for "dynamic" parameters (list of completions generated at runtime by executing an `ion` script?)
- Add support for "scheme" parameters
- Decide where to save the config files
    - Add hook for installation script
    - Adapt initialization code accordingly
- Fix issue: auto-complete does not work if the cursor is on the right edge of a completed parameter (no space is inserted afterwards)
- Cleanup the code, Add comments
- Rebase onto current master and fix merge conflicts
- We might also want to add a new builtin for (re)loading completions at runtime
- In a next step, we also should implement parsers to import completions of other shells/from man-pages.
- Test on Redox (currently only on Linux tested)
- Add a bunch of completion configs.

**Fixes**: #397

**State**: WIP

**Blocking/related**: None that I know of.

**Other**:
- Is the direction of this PR/proposal good? Or would you rather do it completely script-based (like other shells do)? I think the major advantage of a config-based approach is, that it's easier to set up a new completion ruleset.
- This is WIP and not ready to merge, however I wanted to have you have a look at it before I invest more time in it. Doesn't make sense to continue my efforts if you don't even want such a solution.

I'm open for feedback, however I'll also be busy in the next days.

### CODE REVIEW

**Comment by mmstick** [comment]
@BafDyce You may want to PR this [here](https://gitlab.redox-os.org/redox-os/ion).

**Comment by mmstick** [comment]
I'm wondering if [RON](https://github.com/ron-rs/ron/) might be a better format than TOML for this?

**Comment by mmstick** [comment]
Thanks for looking into this. It's massive undertaking. This looks like it's going in the right direction. We definitely need the ability to parse completions from man pages.

**Comment by BafDyce** [comment]
@mmstick: Sure, is it possible to create an account there or should I use the 'login via github' option?

I can look into RON, I just used TOML because it's used often in the Rust ecosystem. Also I agree to you that we need a way to parse man pages.

**Comment by mmstick** [comment]
@BafDyce Yes, it'd be good to have the PR there. RON might work a bit better in this case. TOML syntax is a bit awkward for the complex rules like we may need here.

**Pull request closed without merging**
