### PR TITLE
Allow builtins to be executed as part of pipelines

### LINKED ISSUE #379: Execute Builtins Within Pipeline Execution
If a builtin needs to be piped, we should do precisely that. We should achieve this by creating new file descriptors, and mapping the stdout and stderr of these builtin commands to these file descriptors.

### LINKED ISSUE #454: Parsing Issue w/ && Operator
I'm not sure why this is at the moment, but:

```sh
matches Foo '([A-Z])\w+' && echo true
```

Gives the following output:

```
ion: syntax error: '(' at position 13 is out of place
```

But this:

```sh
matches Foo '([A-Z])\w+'; echo true
```

Gives:

```
true
```

I've also noticed that this:

```sh
matches Foo '[A-Z]\w+' && echo true
```

Gives no output, but this does:

```sh
matches Foo '[A-Z]\w+'; echo true
```

Likely the same issue, and likely in the `StatementSplitter` logic.

### PR DESCRIPTION
**Pull request by huntergoldstein**
**Problem**: Currently if we have a builtin to be run as part of a pipeline, we just take the job, reconstruct it, and run a sub-process such as `ion -c builtin arg1 arg2`. This is problematic as it forces `ion` to re-parse the given arguments which is inefficient and bug prone ( #454 ).

**Solution**: Manually manage running builtins as part of a pipeline by forking the current process and executing the builtin in the child process.

**Changes introduced by this pull request**:
- Replaced the use of `Command` in `shell::pipe` with `RefinedJob`; an enumeration that is either an external command or a builtin
- Modified `shell::pipe::pipe` to fork and execute a builtin for the `RefinedJob::Builtin` instance; behavior for `RefinedJob::External` is roughly the same as before: build a `Command`, run `spawn()`.

**Drawbacks**: The use of `RawFd` everywhere might make #364 more difficult.

**Fixes**: Closes #379 ; Closes #454 

**State**: WIP; I want to make sure there are some regression tests in `examples/`. Also this is a 500+- change so letting it sit for review would be good.

**TODO**:
- [x] Determine the redox equivalent for `STDOUT_FILENO` et al
- [x] Add a regression example in `examples/` for piping to / from a builtin #

### CODE REVIEW

**Comment by huntergoldstein** [comment]
Also it seems I forgot to add `STDOUT_FILENO` for redox, so definitely WIP.

**Comment by mmstick** [comment]
Looks good to me so far.

**Comment by huntergoldstein** [comment]
Good to go; I wanted to add an example for `read`, but it doesn't work when `stdin` is not a tty.

**Comment by mmstick** [comment]
Thanks for this work!

**Pull request merged**
