### PR TITLE
Alias reimplementation  #711

### PR DESCRIPTION
**Pull request by ishanjain28**
Alias Reimplementation as discussed in #711 

**Changes introduced by this pull request**:

- Removed Math Expressions parser from `parse_alias`. 
- Alias reimplemented as a keyword exactly like `let` or `export`. 

**Drawbacks**: 
I have made an assumption in my code that might be considered a drawback.

The assumption is that, Any value stored in `alias` will always resolve to a `Statement::Pipeline`, I don't know what should be the appropriate behaviour if it does not resolves to a `Statement::Pipeline`, So, It silently ignores that `PipeItem`. 

**TODOs**:
- Tests(I'll add those if and once this PR is approved)

**Fixes**:
#711 

**State**:
WIP, Everything except for the tests is done.

### CODE REVIEW

**Comment by ishanjain28** [comment]
Apologies for some poor commit messages, I expect the commits to be squashed together.

**Comment by mmstick** [comment]
Any chance you could look into expanding upon it so that it can store a `Vec<Statement>`? It should be possible to do this, for example:

```
$ alias testing = 'echo one; for x in [two, three]; echo $x; end'
$ testing
one
two
three
$ _
```

**Comment by ishanjain28** [comment]
I'll just cover working of my code, 
    alias ll=/usr/bin/ls -l 

`ll` will resolve to `Pipeline{PipeItem{..., command: "ll", Kind: Last}}`, When it goes to `execute_toplevel`, The following 5 changes are made to each element of pipeline.

Check if the command is an alias, If it is, Do the following,
1. Call `StatementSplitter` on the value stored in alias key. 
2. Remove the original PipeItem(One which had the alias as a command, Here on referred to as "Original Pipeitem")
3. Put the new Pipeitems in it's place that were created by calling `StatementSplitter` on alias value.
4. Take args from Original Pipeitem and append them to the last newly created Pipeitem.
5. Change the kind of last newly created PipeItem to that of Original PipeItem.

**Comment by ishanjain28** [comment]
@mmstick I'll try to add support for that. I came up with a different version of this code yesterday that involved calling `execute_toplevel` on each PipeItem generated after expanding alias instead of replacing the original pipeitem but that didn't work well. 

Any pointers on how can I implement that cleanly?

**Comment by mmstick** [comment]
My knowledge is a bit rusty. Let me look through the parsing code to see how I've been doing it.

**Comment by ishanjain28** [comment]
Okay, Cool.

**Comment by mmstick** [comment]
Something like this should get you what you want.

```rust
let mut statements = Vec::new();
for result in StatementSplitter::new(alias_value).map(Statement::parse) {
    statements.push(result?);
}
```

**Pull request closed without merging**
