### PR TITLE
Add polish notation 

### PR DESCRIPTION
**Pull request by glowing-chemist**
Added reverse polish notation support to inbuilt valc command

### CODE REVIEW

**Comment by glowing-chemist** [comment]
Sorry i should have tested better. Please ignore will re commit with fix

**Comment by mmstick** [comment]
Should I close this PR, then?

**Comment by glowing-chemist** [comment]
No its fine, I have fixed the issue now. So feel free to review and merge

**Comment by mmstick** [comment]
Thanks. I've merged the Polish (prefix) notation support for calc.

**Pull request merged**
