### PR TITLE
Fix : src/main.rs : 103 file_completers for all directories in ${PATH}

### PR DESCRIPTION
**Pull request by CapitanCrazy**
Sorry for my awful english

**Problem**: I add some code for add completions from all ${PATH} directories;

**Changes introduced by this pull request**:

- I rewrite ```MultiCompleter``` to use ```Vec<FileCompleter>``` instead of ```FileCompleter```

### CODE REVIEW

**Comment by jackpot51** [comment]
PATH on Redox and Windows is seperated by `;`, not `:`

**Comment by jackpot51** [comment]
Should be if cfg!(unix)

**Comment by CapitanCrazy** [comment]
Ok

**Comment by jackpot51** [comment]
Thanks! Now it will work on all systems that Rust works on!

**Comment by mmstick** [comment]
Probably should have removed the TODO notice since you implemented the feature.

**Pull request merged**
