### PR TITLE
Fix #755

### LINKED ISSUE #755: Ion parsing bug when dealing with string expansion
**Reproduction**: `echo $(let free=[@(free -h)]; echo @free[6]@free[8]/@free[7])`.

**Expected behavior**: Should output `Mem:4Gi/32Gi`.

**Actual behavior**: Outputs `]; echo /)` instead.

**Build information**:
`rustc 1.28.0-dev (a2c4d4e2f 2018-05-28)

ion 1.0.0-alpha (x86_64-unknown-linux-gnu)
rev e3bd8ce699d9c9904687ffaefc6ca1fe105d9788

**Blocking/related**: blocks me from doing the Memory usage option for Ion's `prompt` builtin command: #754

### PR DESCRIPTION
**Pull request by stratact**
This solves the inner `@(...)` expansion issue as mentioned in #755

### CODE REVIEW

**Comment by stratact** [comment]
I can't figure out how to add a proper unit test for it, but an integration test will do for now.

**Comment by mmstick** [comment]
I'll add the unit tests.

**Comment by stratact** [comment]
Thank you :smile_cat:

**Comment by mmstick** [comment]
Thanks! It's great to see the parser become more sound.

**Comment by stratact** [comment]
No problem! It's my pleasure to help :cat:

**Pull request merged**
