### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by Eijebong**
- lazy_static to 1.0
- libloading to 0.5
- rand to 0.4
- ansi_term to 0.10
- users to 0.6

This removes lazy_static 0.2, ansi_term 0.9 and winapi 0.2 from the dependency
tree.

-----

The only outdated dependency is smallvec but it would require https://github.com/redox-os/smallstring/pull/1 to be merged/released.

### CODE REVIEW

**Comment by jackpot51** [comment]
I merged that PR on smallstring, let me know if that helps

**Comment by Eijebong** [comment]
Well as soon as it's released I can bump smallvec here too and everything will be up to date :p

**Comment by jackpot51** [comment]
I can't release it, this is the one on crates.io: https://github.com/jFransham/smallstring/

**Comment by Eijebong** [comment]
Wut, how did I end up on the redox one then ? :o

**Comment by mmstick** [comment]
Can't merge as it is out of sync.

**Pull request merged**
