### PR TITLE
761 parsing bug

### LINKED ISSUE #761: $(^) Parsing Bug
The following command will hang the ion shell:

```
whois $(dig gitlab.com | grep ^gitlab.com)
```

Unsure at this time as to the cause. Either the parser or job execution

### PR DESCRIPTION
**Pull request by emturner**
progress on #761 

sorry about the upstream merges, not sure how to get rid of them

### CODE REVIEW

**Comment by emturner** [comment]
[WIP]

**Comment by stratact** [comment]
Can you squash those commits?

**Comment by stratact** [comment]
@emturner Sorry about the squash suggestion I didn't realized it wouldn't work. I think what you could (or should) do is git checkout your master branch, rebase to the last revision, add a new branch from master and checkout that branch and then cherry-pick all the non "Merge branch 'master'..." commits and push that to your origin. That should make it clean.

**Comment by mmstick** [comment]
You don't have to squash or rebase manually. GitHub does that automatically when I merge.

**Pull request closed without merging**
