### PR TITLE
Fix small error in readme

### PR DESCRIPTION
**Pull request by BafDyce**
Removed just some stray words.

### CODE REVIEW

**Comment by mmstick** [comment]
Thanks! Any ideas for what we could document better?

**Comment by BafDyce** [comment]
Right now, the only thing that comes to my mind would be to improve/add documentation of the builtins, as is already mentioned in #416 Maybe even add some documentation of the various methods. (It's a bit strange that these are one of ions most powerful features and yet there's almost no documentation about them)

This includes the "in-shell" documentation (via `help`) as well as the manual.

**Comment by mmstick** [comment]
Reason for no documentation at the moment is because it would take a bit of effort to document each and every method we support right now. It is a high priority to document them though.

**Comment by BafDyce** [comment]
I see that it takes a lot of effort. (Thats why most projects lack documentation :P) When I have finished the feature-implementations I'm currently working on, I can help documenting! I'll come back to you to ask where I should begin once I am ready.

**Pull request merged**
