### PR TITLE
Implement Aliasing Support

### PR DESCRIPTION
**Pull request by mmstick**
Implements support for creating aliases, resolving issue #215. I've implemented the syntax to utilize the existing `let` keyword, like so:

```sh
let alias ls = "ls --color"
ls -l
# Expands to and executes `ls --color -l`
```

### CODE REVIEW

**Comment by jackpot51** [comment]
I don't like the `let alias` syntax. Would it be difficult to change it to `alias`?

Also, I wonder what happens if you have this:
```
let alias echo = "echo alias"
echo echo
```
Will it correctly echo `alias echo`, or incorrectly echo `alias echo alias`

**Comment by mmstick** [comment]
> I don't like the let alias syntax. Would it be difficult to change it to alias?

I could make it `alias` if you would prefer that.

> Will it correctly echo alias echo, or incorrectly echo alias echo alias?

Indeed, the implementation will expand `echo echo` into `echo alias echo`

**Comment by jackpot51** [comment]
Good to know! I would prefer `alias`, to avoid multiplexing `let` syntax

**Comment by mmstick** [comment]
Okay, it's been changed to use an `alias` keyword instead.

**Comment by jackpot51** [comment]
Thanks @mmstick!

**Pull request merged**
