### PR TITLE
Added some requested calculations methods

### PR DESCRIPTION
**Pull request by mgmoens**
Like requested in my previous PR.

I haven't added XOR, >> or << (because I would have to change the way tokens get parsed, since they are single characters now).

### CODE REVIEW

**Comment by mmstick** [comment]
Thanks!

**Comment by jackpot51** [comment]
This code is now in 3 places, calc, ion, and orbcalc. We need to make it a library, at this point the ion implementation is ahead of the others

**Comment by mmstick** [comment]
Will you be working on adding the `**`, `>>`, and `<<` operations soon? If not, I can do it.

**Comment by mgmoens** [comment]
I don't know, I'm kinda procrastinating a bit too much :). Feel free to do them if you feel like it.

**Comment by mmstick** [comment]
I've implemented them ( https://github.com/redox-os/ion/commit/4ed3dbdf35880a632fe651f524e064bc907b6083 ).

**Pull request merged**
